data(cars)
?cars
head(cars)
plot(cars)
data(cars)
plot(x=cars$speed,y=cars$dist)
plot(x=cars$speed,y=cars$dist)
plot(x=cars$speed,y=cars$dist)
plot(cars)
plot(cars$speed ~ cars$dist)
plot(x=cars$speed,y=cars$dist)
plot(cars$speed ~ cars$dist)
plot(cars$speed ~ cars$dist)
plot(cars$speed ~ cars$dist)
plot(cars$dist ~ cars$speed)
plot(x = cars$dist, y = cars$speed, xlab="Speed")
plot(x = cars$speed, y = cars$dist, xlab="Speed", ylab="Stopping Distance")
data(cars)
plot(cars$dist ~ cars$speed)
plot(x = cars$dist, y = cars$speed, xlab="Speed")
plot(cars$dist ~ cars$speed)
plot(x = cars$dist, y = cars$speed, xlab="Speed")
plot(cars, subtitle = "My Plot")
plot(cars, sub = "My Plot Subtitle")
plot(cars, subtitle = "My Plot Subtitle")
plot(cars, sub = "My Plot Subtitle")
plot(cars, col=2)
plot(cars, col="dark red")
plot(cars, col="red")
plot(cars, col="green")
plot(cars, col="gray")
plot(cars, col="silver")
plot(cars, col="blue")
plot(cars, col="dark blue")
plot(cars, col="dark cyan")
plot(cars, col="cyan")
plot(cars, col="orange")
plot(cars, xlim=c(10,15))
plot(cars, xlim=c(10,15))
plot(cars, ylim=c(100,150))
plot(cars, ylim=c(20,60))
plot(cars, pch=2)
plot(cars, pch=2, type="h")
plot(cars, pch=2, type="o")
plot(cars, pch=2, type="S")
plot(cars, pch=2, type="p")
plot(cars, type="l")
plot(cars, type="h")
plot(cars, type="b")
plot(cars, type="c")
plot(cars, type="s")
plot(cars, type="n")
plot(cars, type="l")
boxplot(mpg ~ cyl, mtcars)
mat <- cbind(Uni05 = (1:100)/21)
boxplot(mat)
mat <- cbind(Uni05 = (1:100)/21, Norm = rnorm(100))
boxplot(mat)
mat <- cbind(XXI = (1:100)/21)
boxplot(mat)
mat <- cbind((1 + 100)/21)
boxplot(mat)
mat <- cbind(1 + 100)
boxplot(mat)
hist(mtcars$mpg)
barplot(marital)
head(marital)
data(marital)
view(marital)
View(marital)
barplot(marital)
barplot(marital,legend = row.names(marital))
barplot(marital,beside=TRUE)
barplot(t(marital))
barplot(t(marital), beside=TRUE)
barplot(mtcars$cyl)
barplot(mtcars$cyl,legend = row.names(mtcars$cyl))
barplot(mtcars,legend = row.names(mtcars$cyl))
counts <- table(mtcars$gear)
barplot(counts, main="Car Distribution",
xlab="Number of Gears")
counts <- table(mtcars$gear)
barplot(counts, main="Car Distribution", horiz=TRUE,
names.arg=c("3 Gears", "4 Gears", "5 Gears"))
counts <- table(mtcars$gear)
barplot(counts, main="Car Distribution", horiz=FALSE,
names.arg=c("3 Gears", "4 Gears", "5 Gears"))
counts <- table(mtcars$gear)
barplot(counts, main="Car Distribution", horiz=TRUE,
names.arg=c("3 Gears", "4 Gears", "5 Gears"))
counts <- table(mtcars$vs, mtcars$gear)
barplot(counts, main="Car Distribution by Gears and VS",
xlab="Number of Gears", col=c("darkblue","red"),
legend = rownames(counts))
counts <- table(mtcars$vs, mtcars$gear)
barplot(counts, main="Car Distribution by Gears and VS",
xlab="Number of Gears", col=c("darkblue","red"),
legend = rownames(counts), beside=TRUE)
counts <- table(mtcars$vs, mtcars$gear)
barplot(counts, main="Car Distribution by Gears and VS",
xlab="Number of Gears", col=c("darkblue","red"),
legend = rownames(counts), beside=FALSE)
counts <- table(mtcars$vs, mtcars$gear)
barplot(counts, main="Car Distribution by Gears and VS",
xlab="Number of Gears", col=c("darkblue","red"),
legend = rownames(counts), beside=FALSE, horiz=TRUE)
counts <- table(mtcars$vs, mtcars$gear)
barplot(counts, main="Car Distribution by Gears and VS",
xlab="Number of Gears", col=c("darkblue","red"),
legend = rownames(counts), beside=TRUE, horiz=TRUE)
data(cars)
knitr::opts_chunk$set(echo = TRUE)
counts <- table(mtcars$gear)
barplot(counts, main="Car Distribution", horiz=TRUE,
names.arg=c("3 Gears", "4 Gears", "5 Gears"))
counts <- table(mtcars$vs, mtcars$gear)
barplot(counts, main="Car Distribution by Gears and VS",
xlab="Number of Gears", col=c("darkblue","red"),
legend = rownames(counts))
counts <- table(mtcars$vs, mtcars$gear)
barplot(counts, main="Car Distribution by Gears and VS",
xlab="Number of Gears", col=c("darkblue","red"),
legend = rownames(counts), beside=TRUE)
counts <- table(mtcars$vs, mtcars$gear)
barplot(counts, main="Car Distribution by Gears and VS",
xlab="Number of Gears", col=c("darkblue","red"),
legend = rownames(counts), beside=TRUE, horiz=TRUE)
